const $=s=>document.querySelector(s);
const generalMessage='Hello, I would like to receive more information about your custom metalwork services.';
const quoteMessage=name=>`Hello, I’m interested in receiving a quote for ${name}. I would like to receive more information.`;
const whatsappUrl=message=>`https://wa.me/${CATALOG.whatsapp}?text=${encodeURIComponent(message)}`;
const image=(file,alt)=>`<img src="assets/${file}" alt="${alt}" loading="lazy" width="900" height="1100">`;
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let observer;if('IntersectionObserver'in window&&!reduced.matches){document.body.classList.add('motion');observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});}
function reveal(root=document){root.querySelectorAll('.reveal').forEach((el,i)=>{el.style.setProperty('--delay',`${i%4*70}ms`);if(observer)observer.observe(el);else el.classList.add('visible');});}
let lastCollection=null;
$('#collection-grid').innerHTML=CATALOG.collections.map((c,i)=>`<button class="collection-card reveal" data-collection="${c.id}" aria-controls="products" aria-expanded="false"><div class="collection-image">${image(c.image,c.name+(c.reference?' — reference metalwork detail':''))}<span class="image-num">0${i+1}</span>${c.reference?'<span class="reference-badge">REFERENCE DETAIL</span>':''}</div><h3>${c.name}</h3><p>${c.caption}</p><span class="text-link">View collection <span aria-hidden="true">↗</span></span></button>`).join('');
$('.collection-tabs').innerHTML=CATALOG.collections.map(c=>`<button type="button" data-collection="${c.id}" aria-pressed="false">${c.name}</button>`).join('');
function showCollection(id,scroll=true){const c=CATALOG.collections.find(x=>x.id===id);if(!c)return;lastCollection=id;$('#products').hidden=false;$('#product-title').textContent=c.name;$('#product-count').textContent='03 / MADE TO ORDER';$('#collection-note').hidden=!c.reference;$('#product-grid').innerHTML=c.products.map(([name,desc,materials,file,note],i)=>`<article class="product-card reveal"><div class="product-image">${image(file,note||name)}${note?'<span class="reference-badge">REFERENCE DETAIL</span>':''}</div><div class="product-copy"><span class="eyebrow">0${i+1} / ${c.name.toUpperCase()}</span><h3>${name}</h3><p>${desc}</p><p class="materials">${materials}</p>${note?`<p class="reference-caption">${note}.</p>`:''}<a class="text-link" href="${whatsappUrl(quoteMessage(name))}" target="_blank" rel="noopener noreferrer" aria-label="Request a quote for ${name}">Request a quote <span aria-hidden="true">↗</span></a><button class="brief-link" data-interest="${name}">Or send a project brief →</button></div></article>`).join('');document.querySelectorAll('.collection-tabs button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.collection===id)));document.querySelectorAll('.collection-card').forEach(b=>b.setAttribute('aria-expanded',String(b.dataset.collection===id)));$('#interest').value=c.name;reveal($('#product-grid'));if(scroll){$('#product-title').focus({preventScroll:true});$('#products').scrollIntoView({behavior:reduced.matches?'auto':'smooth'});}}
document.querySelectorAll('[data-collection]').forEach(b=>b.addEventListener('click',()=>{history.replaceState(null,'',`#collection-${b.dataset.collection}`);showCollection(b.dataset.collection);}));
document.querySelectorAll('.back').forEach(b=>b.addEventListener('click',()=>{$('#products').hidden=true;document.querySelectorAll('.collection-card').forEach(x=>x.setAttribute('aria-expanded','false'));history.replaceState(null,'','#collections');document.querySelector(`.collection-card[data-collection="${lastCollection}"]`)?.focus({preventScroll:true});$('#collections').scrollIntoView();}));
document.querySelectorAll('.whatsapp-general').forEach(a=>{a.href=whatsappUrl(generalMessage);a.target='_blank';a.rel='noopener noreferrer';});
const menu=$('.menu-toggle');function closeMenu(){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open menu');$('#nav').classList.remove('open');}menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu');$('#nav').classList.toggle('open',open);});document.querySelectorAll('#nav a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#nav').classList.contains('open')){closeMenu();menu.focus();}});
$('#interest').insertAdjacentHTML('beforeend',CATALOG.collections.map(c=>`<optgroup label="${c.name}"><option>${c.name}</option>${c.products.map(p=>`<option>${p[0]}</option>`).join('')}</optgroup>`).join('')+'<option>Other / bespoke project</option>');
$('#product-grid').addEventListener('click',e=>{const b=e.target.closest('[data-interest]');if(b){$('#interest').value=b.dataset.interest;$('#contact').scrollIntoView();$('#lead-form input[name="name"]').focus({preventScroll:true});}});
const form=$('#lead-form');let requestId=crypto.randomUUID();let busy=false;form.addEventListener('input',()=>{requestId=crypto.randomUUID();});
form.addEventListener('submit',async e=>{e.preventDefault();if(busy||!form.reportValidity())return;busy=true;const submit=form.querySelector('button[type="submit"]');submit.disabled=true;submit.setAttribute('aria-busy','true');const status=$('#form-status');status.className='';status.textContent='Sending your request…';$('#form-fallback').hidden=true;const data=Object.fromEntries(new FormData(form));data.requestId=requestId;const control=new AbortController();const timer=setTimeout(()=>control.abort(),20000);try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:control.signal});const result=await r.json();if(!r.ok||!result.ok)throw new Error(result.error||'Your request could not be sent. Please try again or contact us on WhatsApp.');status.className='success';status.textContent='Thank you. Your request has been sent successfully. We will contact you soon.';form.reset();requestId=crypto.randomUUID();}catch(err){status.className='error';status.textContent=err.name==='AbortError'?'The request timed out. Please try again or contact us on WhatsApp.':err.message;$('#form-fallback').hidden=false;}finally{clearTimeout(timer);busy=false;submit.disabled=false;submit.removeAttribute('aria-busy');}});
let ticking=false;function onScroll(){if(!ticking){requestAnimationFrame(()=>{$('#header').classList.toggle('scrolled',scrollY>20);if(!reduced.matches&&scrollY<innerHeight)document.documentElement.style.setProperty('--parallax',`${Math.min(scrollY*.12,75)}px`);ticking=false;});ticking=true;}}window.addEventListener('scroll',onScroll,{passive:true});onScroll();
$('#year').textContent=new Date().getFullYear();function restoreHash(){const id=location.hash.replace('#collection-','');if(CATALOG.collections.some(c=>c.id===id))showCollection(id);}window.addEventListener('hashchange',restoreHash);restoreHash();reveal();
